version: "3.8"  # Use a stable version

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: LINKSBASE
      POSTGRES_USER: modev
      POSTGRES_PASSWORD: zaq1@WSX
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: linkforge_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: linkforge_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: modev
      RABBITMQ_DEFAULT_PASS: zaq1@WSX

  celery:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - rabbitmq
